# Jdk,Jreインストール
apt-get install -y default-jre default-jdk && \

# sbtインストール	 
wget https://github.com/sbt/sbt/releases/download/v0.13.15/sbt-0.13.15.zip && \	 
apt-get install -y unzip && \
unzip sbt-0.13.15.zip && \	 
mv sbt /usr/local/sbt && \
echo "export PATH=/usr/local/sbt/bin:$PATH" >> /root/.bashrc && \

# playインストール
# wget https://downloads.typesafe.com/typesafe-activator/1.3.12/typesafe-activator-1.3.12.zip  && \
# apt-get install -y unzip && \


# activetor run
CMD ["sbt","run"]

EXPOSE 3306

